# Generated by Django 2.1.7 on 2019-02-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20190228_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='../static/img/no_photo.png', upload_to='products_images'),
        ),
    ]
